# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Xelig
version:      0.04
version_from: lib/Xelig.pm
installdirs:  perl
requires:
    Acme::Util:                    0.09
    Scalar::Util:                  0
    XML::Parser:                   0
    XML::Simple:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
